follow = true # follow symlinks, so we can symlink ~\Documents to ~\OneDrive\Documents
[git]
  autoPush = true
[cd]
  command = "pwsh"
  args = ["-NoProfile", "-NoLogo"]
[interpreters.ps1]
  command = "pwsh"
  args = ["-NoLogo", "-NoProfile"]