---
- name: Install packages on Ubuntu
  hosts: localhost
  become: true

  tasks:
    - name: Update the apt package index
      apt:
        update_cache: yes

    - name: Update or upgrade packages
      apt:
        name: "{{ item }}"
        state: latest  # Ensure the latest version is installed
      loop:
        - qemu-system-x86
        - qemu-utils

    - name: Install packages
      apt:
        name: "{{ item }}"
        state: present  # Ensure package does not get upgraded if already present
      loop:
        - neovim