---
- name: Install packages on Ubuntu
  hosts: localhost
  vars:
     - fonts_dir: "{{ ansible_env.HOME }}/.local/share/fonts"
     - go_version: 1.23.3
     - nvm_version: 0.40.0
  become: true

  tasks:
    - name: Update the apt package index
      apt:
        update_cache: yes

    - name: Update or upgrade packages
      apt:
        name: "{{ item }}"
        state: latest  # Ensure the latest version is installed
      loop:
        - gcc 
        - qemu-system-x86
        - qemu-utils
        - make
        - jq
        - ripgrep
        - delta
        - unzip

    - name: Install packages
      apt:
        name: "{{ item }}"
        state: present  # Ensure package does not get upgraded if already present
      loop:
        - neovim

    # Install Docker

    - name: Install Docker
      block:
        - name: Add an Apt signing key, uses whichever key is at the URL
          ansible.builtin.apt_key:
            url: https://download.docker.com/linux/ubuntu/gpg
            state: present

        - name: Add Docker repository
          apt_repository:
            repo: deb https://download.docker.com/linux/ubuntu noble stable
            state: present

        - name: Install Docker
          apt:
            name: docker-ce
            state: present
            update_cache: yes

        - name: Start Docker service
          service:
            name: docker
            state: started
            enabled: yes

    # Install Go

    - stat:
        path: "/usr/local/go/bin/go"
      register: go_installed

    - name: Install Go
      block:
        - name: Download Go tar file
          command: wget https://go.dev/dl/go{{go_version}}.linux-amd64.tar.gz

        - name: Delete previous installation
          command: rm -rf /usr/local/go

        - name: Extract and move new Go folder to /usr/local
          command: tar -C /usr/local -xzf go{{go_version}}.linux-amd64.tar.gz

        - name: Delete downloaded tar file
          shell: rm -rf go{{go_version}}.linux-amd64.tar.gz*

        - name: Add Go binary path to ~/.profile
          lineinfile:
            path: ~/.profile
            line: 'export PATH=$PATH:/usr/local/go/bin:$GOPATH/bin'
            create: true
            state: present

        - name: Source updated profile
          shell: . ~/.profile
      when: go_installed.stat.exists == false

    # test if nvm has been installed by the user desired
    - stat:
        path: "$HOME/.nvm"
      register: nvm_path

    - name: Setup NodeVersionManager and install node version
      block:
        - name: Install nvm
          shell: >
            curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v{{nvm_version}}/install.sh | bash 
          args:
            executable: /bin/bash
            chdir: "$HOME"
            creates: "$HOME/.nvm/nvm.sh"

        - name: Setup .profile of yournonrootuser
          lineinfile:
            path: ~/.profile
            # This will make sure Node is on the users PATH
            line: source ~/.nvm/nvm.sh 
            create: yes
      when: nvm_path.stat.exists  == false 

    - name: Installing node versions using loop
      shell: >
        source $HOME/.nvm/nvm.sh && nvm install {{item}}
      args:
        executable: /bin/bash
        chdir: "$HOME"
        creates: "$HOME/.nvm/versions/node/v{{item}}"
      loop:
        - 16
        # - 14.18.3

    - name: Install Fira Code Nerd Font
      block:
        - name: Ensure fonts directory exists
          file:
            path: "{{ fonts_dir }}"
            state: directory
            mode: '0755'

        - name: Download Fira Code Nerd Font
          get_url:
            url: https://github.com/ryanoasis/nerd-fonts/releases/download/v3.3.0/FiraCode.zip
            dest: /tmp/FiraCode.zip
            mode: '0644'
          register: download_result

        - name: Unzip the font archive
          unarchive:
            src: /tmp/FiraCode.zip
            dest: "{{ fonts_dir }}"
            remote_src: yes
          when: download_result.changed

        - name: Update font cache
          command: fc-cache -fv
          when: download_result.changed
          notify: Font cache updated

      vars:
        fonts_dir: "{{ ansible_env.HOME }}/.local/share/fonts"

    - name: Install Starship Prompt
      block:
        - name: Check if Starship is already installed
          stat:
            path: /usr/local/bin/starship
          register: starship_installed

        - name: Prompt user for confirmation to install Starship
          ansible.builtin.pause:
            prompt: "Starship is not installed. Do you want to install it using the shell script? (Press 'y' to continue)"
          when: not starship_installed.stat.exists
          register: user_input

        - name: Install Starship via shell script
          shell: |
            curl -L -sS https://starship.rs/install.sh | sh -s -- --yes
          args:
            executable: /bin/bash
          when:
            - not starship_installed.stat.exists
            - user_input.user_input == 'y'
          register: install_result

        - name: Display installation result
          debug:
            msg: "Starship installation was successful."
          when: install_result is defined and install_result.rc == 0

      rescue:
        - name: Notify user of failed installation
          debug:
            msg: "Starship installation failed. Please check the error and try again."

      always:
        - name: Inform user of current state
          debug:
            msg: >
              {%- if starship_installed.stat.exists -%}
              Starship is already installed.
              {%- else -%}
              Starship was not installed. Skipped by user or failed.
              {%- endif -%}
